---
title: "gun_law_scorecard_analysis"
author: "Wesley Hoy"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
```


```{r}
scorecard <- read_csv("data/giffords_gun_law_scorecard_2021.csv") %>%
  mutate(Grade = substr(Grade, 1, 1)) # Remove + and - from grades for easier data analysis
  

head(scorecard)


scorecard %>%
  filter(Grade == "A") %>%
  nrow()

scorecard %>%
  filter(Grade == "B") %>%
  nrow()

scorecard %>%
  filter(Grade == "C") %>%
  nrow()

scorecard %>%
  filter(Grade == "D") %>%
  nrow()

scorecard %>%
  filter(Grade == "F") %>%
  nrow()
```

As you can see, a majority of states in the US have a low gun law rating, according to Giffords Law Center. Now, let's match up their scores to their gun law rank

```{r}
scorecard %>%
  group_by(Grade) %>%
  summarize(Average_Ranking = mean(Gun_Law_Strength_Rank),
            SD_Ranking = sd(Gun_Law_Strength_Rank),
            Average_Death_Rate_Rank = mean(Gun_Death_Rate_Rank),
            SD_Death_Rate_Rank = sd(Gun_Death_Rate_Rank),
            Averate_Death_Rate_Per_100k = mean(Gun_Deaths_Per_100k),
            SD_Death_Rate_Per_100k = sd(Gun_Deaths_Per_100k)) ->
  scorecard_generalized

head(scorecard_generalized)

ggplot(scorecard_generalized, aes(Grade, Average_Ranking, fill = Grade)) +
  geom_bar(stat="identity") +
  coord_flip() +
  labs(y = "Average Ranking", title = "Average Gun Law Strength Rank For Each Grade For States in the US", subtitle = "Data courtesy of Gilfords Law Center")

ggplot(scorecard_generalized, aes(Grade, Average_Death_Rate_Rank, fill = Grade)) +
  geom_bar(stat="identity") +
  coord_flip() +
  labs(y = "Average Ranking For Death Rate", title = "Average Ranking For Death Rate Rank For Each Grade For States in the US", subtitle = "Data courtesy of Gilfords Law Center")

ggplot(scorecard_generalized, aes(Grade, Averate_Death_Rate_Per_100k, fill = Grade)) +
  geom_bar(stat="identity") +
  coord_flip() +
  labs(y = "Average Death Rate Per 100k", title = "Average Death Rate Per 100k Rank For Each Grade For States in the US", subtitle = "Data courtesy of Gilfords Law Center")


```

# Matching Gun Law Rankings to Likelihood of Hate Crimes

```{r}
hate_crime <- read_csv("data/hate_crime.csv") %>%
  filter(data_year == 2021) %>%
  group_by(state_name) %>%
  summarize(crimes_reported = n()) %>%
  rename(State = state_name) -> hate_crime

hate_crime

hate_crime <- hate_crime %>%
  full_join(scorecard, by ="State") %>%
  filter(!(is.na(Grade)))

hate_crime %>%
  group_by(Grade) %>%
  summarize(avg_crimes_reported = mean(crimes_reported, na.rm=TRUE)) %>%
  ggplot(aes(Grade, avg_crimes_reported)) + 
    geom_bar(stat="identity")

hate_crime %>%
  group_by(Grade) %>%
  summarize(sd_crimes_reported = sd(crimes_reported, na.rm=TRUE)) %>%
  ggplot(aes(Grade, sd_crimes_reported)) + 
    geom_bar(stat="identity")



```

# Ratio of Hate Crimes to Population

```{r}
read_csv("data/countypres_2000-2020.csv") %>%
  rename(State = state) %>%
  filter(year == 2020) %>%
  group_by(State, party) %>%
  summarize(totalvotes = sum(candidatevotes)) %>%
  pivot_wider(names_from=party, values_from=totalvotes) %>%
  mutate(did_trump_win = (REPUBLICAN > DEMOCRAT)) %>%
  select(State, did_trump_win) -> log

log$State <- str_to_title(log$State)

log%>%
  left_join(hate_crime, by = "State") %>%
  group_by(did_trump_win) %>%
  summarize(avg_crimes = mean(crimes_reported, na.rm=TRUE)) %>%
  ggplot(aes(did_trump_win, avg_crimes)) +
    geom_bar(stat="identity") +
    ggtitle("Avg # of Hate Crimes in States Where Trump Won vs. Lost in 2020") +
    labs(x = "Trump Won", y = "Average Number of Hate Crimes Grouped by State")
```


```{r}
read_csv("data/NST-EST2021-alldata.csv") %>%
  rename(State = state) %>%
  left_join(hate_crime, by="State") %>%
  group_by(State) %>%
  summarize(crimes_to_pop = (crimes_reported/pop_2021)) ->
  crimes_to_pop_df


read_csv("data/countypres_2000-2020.csv") %>%
  rename(State = state) %>%
  filter(year == 2020) %>%
  group_by(State, party) %>%
  summarize(totalvotes = sum(candidatevotes)) %>%
  pivot_wider(names_from=party, values_from=totalvotes) %>%
  mutate(did_trump_win = (REPUBLICAN > DEMOCRAT)) %>%
  select(State, did_trump_win) -> trump_to_crimes
  
trump_to_crimes$State <- str_to_title(trump_to_crimes$State)

trump_to_crimes%>%
  left_join(crimes_to_pop_df, by = "State") %>%
  group_by(did_trump_win) %>%
  summarize(avg_crimes = mean(crimes_to_pop, na.rm=TRUE)) %>%
  ggplot(aes(did_trump_win, avg_crimes)) +
    geom_bar(stat="identity") +
    ggtitle("Avg Ratio of Crimes to Population in States Where Trump Won vs. Lost in 2020") +
    labs(x = "Trump Won", y = "Average Ratio of Crimes Grouped by State")


```




